import taichi as ti

from catsim.enums import (
    EUCLIDEAN_DISTANCE,
    INTERACTION_LEVEL_0,
    INTERACTION_LEVEL_1,
    INTERACTION_NO,
    MOVE_PATTERN_PHIS,
)

PLATE_WIDTH, PLATE_HEIGHT = 1500, 1000
CATS_N = 60

# 0 <= FAVORITE_CAT_IDX < CATS_N otherwise favorite cat undefined
FAVORITE_CAT_IDX = 1

OBSERVABLE_ANGLE_SPAN = ti.math.pi / 6

# ----- CAT ----- #
CAT_RADIUS = 0.02 * PLATE_HEIGHT
MOVE_RADIUS = CAT_RADIUS * 2
RADIUS_0 = CAT_RADIUS * 2
RADIUS_1 = RADIUS_0 * 3

# ----- PATTERNS ----- #
MOVE_PATTERN_ID = MOVE_PATTERN_PHIS
DISTANCE = EUCLIDEAN_DISTANCE

# ----- INTERACTIONS ----- #
PROB_INTERACTION = False
BORDER_INTERACTION = True

# ----- VISUALISATION ----- #
COLORS = ti.field(ti.i32, shape=(3,))
COLORS[INTERACTION_NO] = 0x34C924  # green
COLORS[INTERACTION_LEVEL_1] = 0xFFFF00  # yellow
COLORS[INTERACTION_LEVEL_0] = 0xED553B  # red

COLORS_FAV = ti.field(ti.i32, shape=(3,))
COLORS_FAV[INTERACTION_NO] = 0x45B39D  # light green
COLORS_FAV[INTERACTION_LEVEL_1] = 0xFAD7A0  # light yellow
COLORS_FAV[INTERACTION_LEVEL_0] = 0xF1948A  # light red

COLORS_IGN = ti.field(ti.i32, shape=(3,))
COLORS_IGN[INTERACTION_NO] = 0x333333
COLORS_IGN[INTERACTION_LEVEL_1] = 0x545454
COLORS_IGN[INTERACTION_LEVEL_0] = 0x787878
