import catsim.constants as const

# ----- GENERAL ----- #
PLATE_WIDTH, PLATE_HEIGHT = 1500, 1000
PLATE_H_MIN, PLATE_W_MIN = 0, 0
CATS_N = 500000

# ----- CAT ----- #
CAT_RADIUS = 0.0004 * PLATE_HEIGHT
MOVE_RADIUS = CAT_RADIUS * 1.5
RADIUS_0 = CAT_RADIUS * 1.5
RADIUS_1 = RADIUS_0 * 1.5

# ----- PATTERNS ----- #
MOVE_PATTERN_ID = const.MOVE_PATTERN_PHIS_ID
DISTANCE = const.EUCLIDEAN_DISTANCE

# ----- VISUALISATION ----- #
COLOR_LEVEL_0 = const.RED_COLOR
COLOR_LEVEL_1 = const.YELLOW_COLOR
COLOR_LEVEL_NO = const.GREEN_COLOR

FAV_COLOR_LEVEL_0 = const.S_RED_COLOR
FAV_COLOR_LEVEL_1 = const.S_YELLOW_COLOR
FAV_COLOR_LEVEL_NO = const.S_GREEN_COLOR

# # ----- INTERACTIONS ----- #
PROB_INTERACTION = const.DISABLE_PROB_INTER
BORDER_INTER = const.ENABLE_BORDER_INTER

# 0 <= FAVORITE_CAT_IDX < CATS_N otherwise favorite cat undefined
FAVORITE_CAT_IDX = 1
SPAWN_SEED = const.RANDOM_SEED
