# ----- PATTERNS SETTINGS ----- #
MOVE_PATTERN_RANDOM_ID = 0
MOVE_PATTERN_LINE_ID = 1
MOVE_PATTERN_PHIS_ID = 2

EUCLIDEAN_DISTANCE = 0
MANHATTAN_DISTANCE = 1
CHEBYSHEV_DISTANCE = 2

# ----- INTERACTION LEVELS ----- #
INTERACTION_LEVEL_0 = 2
INTERACTION_LEVEL_1 = 1
INTERACTION_NO = 0

# ----- COLORS ----- #
RED_COLOR = 0xED553B
YELLOW_COLOR = 0xFFFF00
GREEN_COLOR = 0x34C924

# ----- PROBABILISTIC INTERACTION ----- #
ENABLE_PROB_INTER = 1
DISABLE_PROB_INTER = 0
