import taichi as ti

# ----- MOVE PATTERNS ----- #
MOVE_PATTERN_RANDOM = 0
MOVE_PATTERN_LINE = 1
MOVE_PATTERN_PHIS = 2

# ----- DISTANCE FUNCTIONS ----- #
EUCLIDEAN_DISTANCE = 0
MANHATTAN_DISTANCE = 1
CHEBYSHEV_DISTANCE = 2

# ----- INTERACTION LEVELS ----- #
INTERACTION_NO = 0
INTERACTION_LEVEL_1 = 1
INTERACTION_LEVEL_0 = 2

# ----- VISIBILITY STATUSES ----- #
NEVER_APPEARED: ti.i8 = 0
VISIBLE: ti.i8 = 1
INVISIBLE: ti.i8 = 2
ALWAYS_VISIBLE: ti.i8 = 3
ALWAYS_INVISIBLE: ti.i8 = 4

# ----- VISUALISATION ----- #
COLORS = ti.field(ti.i32, shape=(3,))
COLORS[INTERACTION_NO] = 0x34C924  # green
COLORS[INTERACTION_LEVEL_1] = 0xFFFF00  # yellow
COLORS[INTERACTION_LEVEL_0] = 0xED553B  # red

COLORS_FAV = ti.field(ti.i32, shape=(3,))
COLORS_FAV[INTERACTION_NO] = 0x45B39D  # light green
COLORS_FAV[INTERACTION_LEVEL_1] = 0xFAD7A0  # light yellow
COLORS_FAV[INTERACTION_LEVEL_0] = 0xF1948A  # light red

COLORS_IGN = ti.field(ti.i32, shape=(3,))
COLORS_IGN[INTERACTION_NO] = 0x333333
COLORS_IGN[INTERACTION_LEVEL_1] = 0x545454
COLORS_IGN[INTERACTION_LEVEL_0] = 0x787878
