import taichi as ti

# ----- MOVE PATTERNS ----- #
MOVE_PATTERN_RANDOM = 0
MOVE_PATTERN_LINE = 1
MOVE_PATTERN_PHIS = 2

# ----- DISTANCE FUNCTIONS ----- #
EUCLIDEAN_DISTANCE = 0
MANHATTAN_DISTANCE = 1
CHEBYSHEV_DISTANCE = 2

# ----- INTERACTION LEVELS ----- #
INTERACTION_NO = 0
INTERACTION_LEVEL_1 = 1
INTERACTION_LEVEL_0 = 2

# ----- VISIBILITY STATUSES ----- #
NEVER_APPEARED: ti.i8 = 0
VISIBLE: ti.i8 = 1
INVISIBLE: ti.i8 = 2
ALWAYS_VISIBLE: ti.i8 = 3
ALWAYS_INVISIBLE: ti.i8 = 4
