# ----- GENERAL ----- #
PLATE_WIDTH, PLATE_HEIGHT = 400, 400
PLATE_H_MIN, PLATE_W_MIN = 0, 0
CATS_N = 2

# ----- CAT ----- #
# MOVE_RADIUS = 0.03 * PLATE_HEIGHT
# RADIUS_0 = 0.02 * PLATE_HEIGHT
# RADIUS_1 = 0.04 * PLATE_HEIGHT
# CAT_RADIUS = 0.01 * PLATE_HEIGHT

CAT_RADIUS = 0.06 * PLATE_HEIGHT
MOVE_RADIUS = CAT_RADIUS
RADIUS_0 = 2 * CAT_RADIUS
RADIUS_1 = 4 * CAT_RADIUS

# ----- PATTERNS ----- #
MOVE_PATTERN_RANDOM_ID = 0

EUCLIDEAN_DISTANCE = 0
MANHATTAN_DISTANCE = 1
CHEBYSHEV_DISTANCE = 2

# ----- VISUALISATION ----- #
WHITE_COLOR = 1
BLACK_COLOR = -1
GREY_COLOR = 0.5

# ----- INTERNALS ----- #
INTERACTION_LEVEL_0 = 2
INTERACTION_LEVEL_1 = 1
INTERACTION_NO = 0
