MOVE_RADIUS = 2.0
RED_RADIUS = 1.0
YELLOW_RADIUS = RED_RADIUS * 2

PLATE_WIDTH, PLATE_HEIGHT = 1500, 1000
PLATE_H_MIN, PLATE_W_MIN = 0, 0

N = 50000

MOVE_PATTERN_RANDOM_ID = 0

RED_INTERACTION_LEVEL = 2
YELLOW_INTERACTION_LEVEL = 1
GREEN_INTERACTION_LEVEL = 0

BLACK_COLOR = -1
WHITE_COLOR = 1
