# ----- GENERAL ----- #
PLATE_WIDTH, PLATE_HEIGHT = 500, 500
PLATE_H_MIN, PLATE_W_MIN = 0, 0
CATS_N = 100

# ----- CAT ----- #
# MOVE_RADIUS = 0.03 * PLATE_HEIGHT
# RADIUS_0 = 0.02 * PLATE_HEIGHT
# RADIUS_1 = 0.04 * PLATE_HEIGHT
# CAT_RADIUS = 0.01 * PLATE_HEIGHT

CAT_RADIUS = 0.02 * PLATE_HEIGHT
MOVE_RADIUS = CAT_RADIUS * 2
RADIUS_0 = CAT_RADIUS * 3
RADIUS_1 = RADIUS_0 * 7

# ----- PATTERNS ----- #
MOVE_PATTERN_RANDOM_ID = 0

EUCLIDEAN_DISTANCE = 0
MANHATTAN_DISTANCE = 1
CHEBYSHEV_DISTANCE = 2

# ----- VISUALISATION ----- #
RED_COLOR = 0xED553B
YELLOW_COLOR = 0xFFFF00
GREEN_COLOR = 0x34C924

# ----- INTERNALS ----- #
INTERACTION_LEVEL_0 = 2
INTERACTION_LEVEL_1 = 1
INTERACTION_NO = 0
